services:
  postgresql:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:8.2-alpine'
    ports:
      - '6379:6379'
    command: redis-server
