services:
  postgresql:
    image: 'postgres:18.1-bookworm'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
