spring:
  application:
    name: quiet-chatter
  web:
    resources:
      add-mappings: false
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: hidden
    username: hidden
    password: hidden
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  flyway:
    enabled: true
    baseline-on-migrate: true
  threads:
    virtual:
      enabled: true
  data:
    redis:
      url: redis://localhost:6379
      repositories:
        enabled: false
naver:
  api:
    client-id: hidden
    client-secret: hidden

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: true

jwt:
  secret-key: veryveryveryveryLongSecretKeyForLocalDevelopment
