spring:
  data:
    redis:
      url: hidden
  datasource:
    url: hidden

app:
  cors:
    allowed-origins:
      - "https://quiet-chatter.com"
  cookie:
    domain: "api.quiet-chatter.com"
    secure: true
    same-site: Lax
