spring:
  application:
    name: quiet-chatter
  datasource:
    url: hidden
    username: hidden
    password: hidden
  jpa:
    hibernate:
      ddl-auto: update

naver:
  api:
    client-id: hidden
    client-secret: hidden

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: true
