spring:
  data:
    redis:
      url: hidden
  datasource:
    url: hidden

app:
  cors:
    allowed-origins:
      - "https://dev.quiet-chatter.com"
      - "http://localhost:5173"
      - "http://127.0.0.1:5173"
  cookie:
    domain: "dev-api.quiet-chatter.com"
    secure: true
    same-site: Lax
